kind: pipeline
name: default

workspace:
  base: /go
  path: /

  #clone:
  #disable: true


steps:
  - name: docker-workspace-fix
    image: golang:1.9.1
    commands:
      - mkdir -p /go/src/github.com/terraform-providers
      - cd /go/src/github.com/terraform-providers
      - git clone $DRONE_REPO_LINK
      - cd terraform-provider-spotinst
      - git checkout $DRONE_COMMIT

  - name: install
    image: golang:1.9.1
    commands:
      - cd /go/src/github.com/terraform-providers/terraform-provider-spotinst
      - bash scripts/gogetcookie.sh
      - go get github.com/kardianos/govendor

  - name: build
    image: golang:1.9.1
    commands:
      - cd /go/src/github.com/terraform-providers/terraform-provider-spotinst
      - bash scripts/gogetcookie.sh
      - go get github.com/kardianos/govendor
      - make test
      - make vendor-status
      - make vet
        # - make website-test
  - name: website
    image: hashicorp/middleman-hashicorp:0.3.35
    detach: true
    commands:
      - mkdir -p /tmp/src/
      - mkdir -p /ext/providers/spotinst
      - rm -rf /website
      - cd /tmp/src
      - git clone https://github.com/hashicorp/terraform-website.git
      - ln -s /go/src/github.com/terraform-providers/terraform-provider-spotinst/website /website
      - ln -s /go/src/github.com/terraform-providers/terraform-provider-spotinst/website /ext/providers/spotinst/website
      - ln -s /tmp/src/terraform-website/content /terraform-website
      - ls -al /website/*
      - mkdir -p /website/docs/assets
      - mkdir -p /website/docs/layouts
      - ln -s /tmp/src/terraform-website/content/source/assets /website/docs/assets
      - ln -s /tmp/src/terraform-website/content/source/layouts /website/docs/layouts
      - cd /terraform-website
      - ls -al /website
      - /entrypoint.sh bundle exec middleman server
    ports:
    - 4567
  - name: website-test
    image: hashicorp/middleman-hashicorp:0.3.35
    commands:
      - ls /go/src
      - cd /
      - git clone https://github.com/hashicorp/terraform-website.git
      - cd /terraform-website
      - until curl -sS http://website:4567/ > /dev/null; do sleep 1; done
      - /terraform-website/content/scripts/check-links.sh "http://website:4567/docs/providers/spotinst"


