kind: pipeline
name: default

workspace:
  base: /go
  path: /

clone:
  disable: true


steps:
  - name: docker-workspace-fix
    image: golang:1.9.1
    commands:
      - mkdir -p /go/src/github.com/terraform-providers
      - cd /go/src/github.com/terraform-providers
      - git clone $DRONE_REPO_LINK
      - cd terraform-provider-spotinst
      - git checkout $DRONE_COMMIT

  - name: install
    image: golang:1.9.1
    commands:
      - cd /go/src/github.com/terraform-providers/terraform-provider-spotinst
      - bash scripts/gogetcookie.sh
      - go get github.com/kardianos/govendor

  - name: build
    image: golang:1.9.1
    commands:
      - cd /go/src/github.com/terraform-providers/terraform-provider-spotinst
      - bash scripts/gogetcookie.sh
      - go get github.com/kardianos/govendor
      - make test
      - make vendor-status
      - make vet
        # - make website-test
  - name: website-test
    image: hashicorp/middleman-hashicorp:0.3.35
    commands:
      - cd /
      - git clone https://github.com/hashicorp/terraform-website.git
      - cd /terraform-website
        # - until curl -sS http://$WEBSITE_SERVICE_HOST:4567/ > /dev/null; do sleep 1; done
      - /terraform-website/content/scripts/check-links.sh "http://$WEBSITE_SERVICE_HOST:4567/docs/providers/spotinst"

services:
  - name: website
    image: hashicorp/middleman-hashicorp:0.3.35
    commands:
      - cd /
      - git clone https://github.com/hashicorp/terraform-website.git
      - cd /terraform-website
      - mkdir -p /ext/providers/spotinst/website
      - ln -s /go/src/github.com/terraform-providers/terraform-provider-spotinst/website /website
      - ln -s /go/src/github.com/terraform-providers/terraform-provider-spotinst/website /ext/providers/spotinst/website
      - /entrypoint.sh bundle exec middleman server
    ports:
    - 4567

